version: '3'

networks:
  default:
  # Use the previously created public network "traefik_public", shared with other
  # services that need to be publicly available via this Traefik
  traefik_public:
    external: true

services:
  webapp:
    image: bcrowe/todoapp:latest
    networks:
      - default
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.todoapp.loadbalancer.server.port=3000"
        - "traefik.http.services.todoapp.loadbalancer.passhostheader=true"
        - "traefik.http.services.todoapp.loadbalancer.sticky.cookie.name=todoapp"
        - "traefik.http.routers.todoapp.entrypoints=https"
        - "traefik.http.routers.todoapp.rule=Host(`todoapp1.fairwarning.com`)"
        - "traefik.http.routers.todoapp.tls=true"
    environment:
      - "TODOAPP_APP_PORT=3000"
      - "TODOAPP_DATABASE_HOSTNAME=mongodb"
      - "TODOAPP_DATABASE_PORT=27017"
      - "TODOAPP_DATABASE_NAME=todoapp"
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:4.2.2-bionic
    networks:
      - default
    deploy:
      labels:
        - "traefik.enable=false"
