jwt_secret: TODOAPP_JWT_SECRET
session_time: TODOAPP_SESSION_TIME
app:
  port: TODOAPP_APP_PORT
database:
  user: TODOAPP_DATABASE_USER
  password: TODOAPP_DATABASE_PASSWORD
  hostname: TODOAPP_DATABASE_HOSTNAME
  port: TODOAPP_DATABASE_PORT
  name: TODOAPP_DATABASE_NAME