name: docker_build

on: 
  push:
    branches:
      - 'main'
env:
  DOCKER_IMAGE_NAME: todoapp
  DOCKER_IMAGE_VERSION: latest
  DOCKER_REGISTRY: bcrowe

jobs:
  runs-on: ubunut-latest
  steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_VERSION }}"